name: Unit

on:
  workflow_dispatch:
  push:
    branches:
    - babylon
    - unit-test
  pull_request:

jobs:
    job_unit_test:
        name: Unit test
        runs-on: ubuntu-latest

        container:
            image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

        steps:
        - name: Clone
          uses: actions/checkout@v4

        - name: Build and Run unit tests
          run: |
            cd unit-tests/
            cmake -Bbuild -H. && make -C build && make -C build test